version: '3.8'

services:
  db:
    image: postgres:latest  # Utilisation de l'image officielle de PostgreSQL
    container_name: immobilier_db  # Nom du conteneur pour PostgreSQL
    environment:
      POSTGRES_USER: admin  # Nom d'utilisateur pour PostgreSQL
      POSTGRES_PASSWORD: rajarabii1  # Mot de passe pour PostgreSQL
      POSTGRES_DB: postgres  # Nom de la base de données
    ports:
      - "5433:5432"  # Expose le port 5432 pour l'accès à la base de données
    volumes:
      - immobilier_db_data:/var/lib/postgresql/data  # Persistance des données
    networks:
      - immobilier_network  # Réseau pour connecter les services

  app:
    build:
      context: .  # Chemin du Dockerfile pour l'application
    container_name: immobilier_app  # Nom du conteneur pour l'application
    depends_on:
      - db  # Démarrer 'db' avant 'app'
    environment:
      DATABASE_URL: postgresql://admin:rajarabii1@db:5432/postgres
                     # URL de connexion PostgreSQL
    networks:
      - immobilier_network
    volumes:
      - .:/usr/src/app  # Monter le répertoire courant pour que l'app puisse accéder aux fichiers
  # Monter le répertoire courant pour que l'app puisse accéder aux fichiers
  
volumes:
  immobilier_db_data:  # Volume pour stocker les données PostgreSQL

networks:
  immobilier_network:  # Réseau pour connecter l'application et la base de données
    driver: bridge
